import type { Metadata } from 'next';
import { NextIntlClientProvider, hasLocale } from 'next-intl';
import { notFound } from 'next/navigation';
import { routing } from '@/i18n/routing';
// import { ReactNode } from 'react';
import styles from './App.module.scss';
import { Header, Footer, Query, Response } from '@/components';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function LocaleLayout({
  // children,
  params,
}: {
  // children: ReactNode;
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }

  return (
    <NextIntlClientProvider>
      <div className={styles.app}>
        <Header />
        <Query />
        <Response />
        {/* {children} */}
        <Footer />
      </div>
    </NextIntlClientProvider>
  );
}
